services:
  db:
    image: postgres:latest
    container_name: webshop_db
    restart: always
    ports:
      - '3001:3001'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: webshop
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: .
    image: webshop_backend
    container_name: webshop_backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      POSTGRES: 'postgres://user:1234@db:3001/webshop'
    depends_on:
      - db

  frontend:
    build:
      dockerfile: Dockerfile.nginx
    image: webshop_frontend
    container_name: webshop_frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  db_data:
